---
title: "Oct 7 2024 Class"
format: html
editor: visual
---

```{r}
#Set up
rm(list=ls())
library(here)
library(tidyverse)
```

```{r}
tomatoes <- read.csv(here("Data", "tomato_data.csv")) #read in the data
```

```{r}
glimpse(tomatoes) #look at the dataset
```

Assign data types –\> Change the columns to factor data type (nominal)

```{r}
tomatoes$Plant_number <- as.factor(tomatoes$Plant_number)

tomatoes$Treatment <- as.factor(tomatoes$Treatment)
```

```{r}
levels(tomatoes$Treatment) #notice no data validation, need to fix factor levels
```

```{r}
fix <- which(tomatoes$Treatment == "control")
tomatoes$Treatment[fix] <- "Control"
```

```{r}
fix2 <- which(tomatoes$Treatment == "fertilizer")
tomatoes$Treatment[fix2] <- "Fertilizer"

levels(tomatoes$Treatment) #still shows all original levels so now need to say...

tomatoes$Treatment <- factor(tomatoes$Treatment) #then read the above line of code again to get the updated levels
```

## Now look at summary function

```{r}
test <- c(2, 4, 6, 8, 10, 12, 14, 16, 18, 20)
summary(test)
```

Looking at summary some more

```{r}
grades <- c(90, 94, 96, 90, 84, 86)
summary(grades)
```

Now a different way

```{r}
quantile(grades, probs = c(0, 0.25, 0.5, 0.75, 1))
```
